name: First Workflow
on: workflow_dispatch # Enable manual trigger
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "Hello World!"
      - name: Fix Something
        run: echo "Fixing Something"
      - name: Print Goodbye
        run: echo "Done - bye!"